import { FoodItem, FoodCategory } from '@/types/food';

export const mockFoods: FoodItem[] = [
  {
    id: '1',
    name: 'Margherita Pizza',
    description: 'Classic pizza with tomato sauce, mozzarella, and fresh basil',
    price: 12.99,
    image: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80',
    category: 'pizza',
    rating: 4.8,
    prepTime: 20,
    isVeg: true,
    isSpicy: false,
    isPopular: true,
  },
  {
    id: '2',
    name: 'Chicken Burger',
    description: 'Juicy chicken patty with lettuce, tomato, and special sauce',
    price: 9.99,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1098&q=80',
    category: 'burgers',
    rating: 4.6,
    prepTime: 15,
    isVeg: false,
    isSpicy: true,
    isPopular: true,
  },
  {
    id: '3',
    name: 'Caesar Salad',
    description: 'Fresh romaine lettuce with Caesar dressing, croutons, and parmesan',
    price: 8.99,
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80',
    category: 'salads',
    rating: 4.5,
    prepTime: 10,
    isVeg: true,
    isSpicy: false,
    isPopular: false,
  },
  {
    id: '4',
    name: 'Pasta Carbonara',
    description: 'Spaghetti with creamy egg sauce, pancetta, and parmesan',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1612874742237-6526229898c7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80',
    category: 'pasta',
    rating: 4.7,
    prepTime: 25,
    isVeg: false,
    isSpicy: false,
    isPopular: true,
  },
  {
    id: '5',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with a molten center, served with vanilla ice cream',
    price: 6.99,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291772?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80',
    category: 'desserts',
    rating: 4.9,
    prepTime: 15,
    isVeg: true,
    isSpicy: false,
    isPopular: true,
  },
];

export const mockCategories: FoodCategory[] = [
  { id: 'pizza', name: 'Pizza', icon: '🍕' },
  { id: 'burgers', name: 'Burgers', icon: '🍔' },
  { id: 'pasta', name: 'Pasta', icon: '🍝' },
  { id: 'salads', name: 'Salads', icon: '🥗' },
  { id: 'desserts', name: 'Desserts', icon: '🍰' },
  { id: 'drinks', name: 'Drinks', icon: '🥤' },
];
